name: ggpp
version: 0.1.3
summary: A simple GIT project patcher
description: |
  A simple GIT project patcher.
  It's APT for patches.
confinement: strict
base: core18
grade: stable

parts:
  ggpp:
    plugin: dump
    source: https://github.com/glenndehaan/ggpp/releases/download/v$SNAPCRAFT_PROJECT_VERSION/ggpp-linux-snapcraft.tar.gz

plugs:
  config-files:
    interface: system-files
    write:
      - /etc
      - /home
      - /opt
      - /root
      - /tmp
      - /usr
      - /var

apps:
  ggpp:
    command: ggpp-linux
    plugs:
      - network
      - config-files
